import type { Metadata } from "next";
import "./globals.css";
import { Inter, Poppins, Roboto } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/providers";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable} ${roboto.variable}`}>
      <body className="font-sans">
        <Toaster
          toastOptions={{
            style: {
              fontWeight: "600",
              fontSize: "14px",
              fontFamily: "sans-serif",
            },
          }}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
